In [ ]:
from google.colab import files

uploaded = files.upload()

pointFiles = []

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  pointFiles.append(fn)

In [ ]:
with open(pointFiles[0]) as f:
    lineNum = 0
    header = []
    body = []
    separators = []
    readBody = False
    for line in f:
        #print(f'Line[{lineNum}]: \t{line}')
        if(not readBody): 
          header.append(line)
        else:
          body.append(line)
        lineNum += 1
        if line.startswith('end_header'):
          readBody = True
        if line.startswith('element'):
          parse = line.split(' ')
          separators.append({'name': parse[1], 'num': int(parse[2]) })

Line[0]: 	ply

Line[1]: 	format ascii 1.0

Line[2]: 	comment Created by Blender 2.80 (sub 75) - www.blender.org, source file: 'red_room.blend'

Line[3]: 	element vertex 124

Line[4]: 	property float x

Line[5]: 	property float y

Line[6]: 	property float z

Line[7]: 	property float nx

Line[8]: 	property float ny

Line[9]: 	property float nz

Line[10]: 	property float s

Line[11]: 	property float t

Line[12]: 	element face 62

Line[13]: 	property list uchar uint vertex_indices

Line[14]: 	end_header

Line[15]: 	-0.250000 0.281250 0.312500 0.000000 1.000000 0.000000 0.250000 0.312500

Line[16]: 	-0.250000 0.281250 0.406250 0.000000 1.000000 0.000000 0.250000 0.406250

Line[17]: 	0.312500 0.281250 0.406250 0.000000 1.000000 0.000000 -0.312500 0.406250

Line[18]: 	0.312500 0.281250 0.312500 0.000000 1.000000 -0.000000 -0.312500 0.312500

Line[19]: 	0.312500 0.281250 0.312500 1.000000 -0.000000 0.000000 0.281250 0.312500

Line[20]: 	0.312500 0.281250 0.406250 1.000000 -0.000000 0.000000 0.

In [ ]:
sections = []
prev = 0
for i in range(len(separators)):
  sections.append({'name': separators[i]['name'], 'data': []})
  for l in body[prev:prev+separators[i]['num']]:
    l = l.strip('\n')
    l = l.strip('\t')
    fList = [float(x) for x in l.split(' ')]
    sections[i]['data'].append(fList)
  prev = separators[i]['num']

In [ ]:
import numpy as np
vertices = np.array(sections[0]['data'])
faces = np.array(sections[1]['data'])

In [ ]:
DECIMATION_CONSTANT = 10

decimated_vert = []

for i in range(len(vertices)):
  if(i % DECIMATION_CONSTANT == 0):
    decimated_vert.append(vertices[i])

print(len(decimated_vert))

In [ ]:
print(vertices)

[[-0.25     0.28125  0.3125   0.       1.       0.       0.25     0.3125 ]
 [-0.25     0.28125  0.40625  0.       1.       0.       0.25     0.40625]
 [ 0.3125   0.28125  0.40625  0.       1.       0.      -0.3125   0.40625]
 [ 0.3125   0.28125  0.3125   0.       1.      -0.      -0.3125   0.3125 ]
 [ 0.3125   0.28125  0.3125   1.      -0.       0.       0.28125  0.3125 ]
 [ 0.3125   0.28125  0.40625  1.      -0.       0.       0.28125  0.40625]
 [ 0.3125  -0.28125  0.40625  1.      -0.       0.      -0.28125  0.40625]
 [ 0.3125  -0.28125  0.3125   1.      -0.       0.      -0.28125  0.3125 ]
 [ 0.3125  -0.28125  0.3125   0.      -1.       0.       0.3125   0.3125 ]
 [ 0.3125  -0.28125  0.40625  0.      -1.       0.       0.3125   0.40625]
 [-0.25    -0.28125  0.40625  0.      -1.       0.      -0.25     0.40625]
 [-0.25    -0.28125  0.3125   0.      -1.       0.      -0.25     0.3125 ]
 [-0.25     0.28125  0.3125   0.       0.      -1.       0.25     0.28125]
 [ 0.3125   0.28125  0.31

In [ ]:
print(faces)

[[  3.   0.   1.   2.]
 [  3.   0.   2.   3.]
 [  3.   4.   5.   6.]
 [  3.   4.   6.   7.]
 [  3.   8.   9.  10.]
 [  3.   8.  10.  11.]
 [  3.  12.  13.  14.]
 [  3.  12.  14.  15.]
 [  3.  16.  17.  18.]
 [  3.  16.  18.  19.]
 [  3.  20.  21.  22.]
 [  3.  20.  22.  23.]
 [  3.  24.  25.  26.]
 [  3.  24.  26.  27.]
 [  3.  28.  29.  30.]
 [  3.  28.  30.  31.]
 [  3.  32.  33.  34.]
 [  3.  32.  34.  35.]
 [  3.  36.  37.  38.]
 [  3.  36.  38.  39.]
 [  3.  40.  41.  42.]
 [  3.  40.  42.  43.]
 [  3.  44.  45.  46.]
 [  3.  44.  46.  47.]
 [  3.  48.  49.  50.]
 [  3.  48.  50.  51.]
 [  3.  52.  53.  54.]
 [  3.  52.  54.  55.]
 [  3.  56.  57.  58.]
 [  3.  56.  58.  59.]
 [  3.  60.  61.  62.]
 [  3.  60.  62.  63.]
 [  3.  64.  65.  66.]
 [  3.  64.  66.  67.]
 [  3.  68.  69.  70.]
 [  3.  68.  70.  71.]
 [  3.  72.  73.  74.]
 [  3.  72.  74.  75.]
 [  3.  76.  77.  78.]
 [  3.  76.  78.  79.]
 [  3.  80.  81.  82.]
 [  3.  80.  82.  83.]
 [  3.  84.  85.  86.]
 [  3.  84.